PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'ailment_data' ('ailment_id' INTEGER NOT NULL, 'ailment_action' INTEGER NOT NULL, 'ailment_detail_1' INTEGER NOT NULL, 'ailment_name' TEXT NOT NULL, PRIMARY KEY('ailment_id'));
INSERT INTO ailment_data VALUES(1,8,1,'슬로우');
INSERT INTO ailment_data VALUES(2,8,2,'헤이스트');
INSERT INTO ailment_data VALUES(3,8,3,'마비');
INSERT INTO ailment_data VALUES(4,8,4,'정지');
INSERT INTO ailment_data VALUES(5,8,5,'바인드');
INSERT INTO ailment_data VALUES(6,8,6,'수면');
INSERT INTO ailment_data VALUES(7,8,7,'스턴');
INSERT INTO ailment_data VALUES(8,8,8,'석화');
INSERT INTO ailment_data VALUES(9,8,9,'구류');
INSERT INTO ailment_data VALUES(10,9,0,'구류(대미지)');
INSERT INTO ailment_data VALUES(11,9,1,'독');
INSERT INTO ailment_data VALUES(12,9,2,'화상');
INSERT INTO ailment_data VALUES(13,9,3,'저주');
INSERT INTO ailment_data VALUES(14,11,0,'매혹');
INSERT INTO ailment_data VALUES(15,12,-1,'어둠');
INSERT INTO ailment_data VALUES(16,13,0,'침묵');
INSERT INTO ailment_data VALUES(17,30,-1,'즉사');
INSERT INTO ailment_data VALUES(18,3,-1,'넉백');
INSERT INTO ailment_data VALUES(19,11,1,'혼란');
INSERT INTO ailment_data VALUES(20,9,4,'맹독');
INSERT INTO ailment_data VALUES(21,56,-1,'천리안');
INSERT INTO ailment_data VALUES(22,59,-1,'회복 저해');
INSERT INTO ailment_data VALUES(23,61,-1,'패닉');
INSERT INTO ailment_data VALUES(24,60,-1,'각인 부여');
INSERT INTO ailment_data VALUES(25,62,-1,'공포');
INSERT INTO ailment_data VALUES(26,69,-1,'순록 변신');
INSERT INTO ailment_data VALUES(27,8,10,'기절');
INSERT INTO ailment_data VALUES(28,9,5,'저주');
INSERT INTO ailment_data VALUES(29,70,-1,'HP 변화');
COMMIT;
