PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'fke_happening_list' ('happening_id' INTEGER NOT NULL, 'happening_name' TEXT NOT NULL, PRIMARY KEY('happening_id'));
INSERT INTO fke_happening_list VALUES(1,'메사르팀');
INSERT INTO fke_happening_list VALUES(2,'바나나 점프');
INSERT INTO fke_happening_list VALUES(3,'바나나 슬라이드');
INSERT INTO fke_happening_list VALUES(4,'아유미의 부채');
INSERT INTO fke_happening_list VALUES(5,'아쿠다이칸 조각');
INSERT INTO fke_happening_list VALUES(6,'간헐천');
INSERT INTO fke_happening_list VALUES(7,'토네이도');
INSERT INTO fke_happening_list VALUES(8,'맞바람');
INSERT INTO fke_happening_list VALUES(9,'폭우');
INSERT INTO fke_happening_list VALUES(10,'지즈');
INSERT INTO fke_happening_list VALUES(11,'낙뢰');
INSERT INTO fke_happening_list VALUES(12,'슈퍼 볼');
INSERT INTO fke_happening_list VALUES(13,'초 저공비행');
INSERT INTO fke_happening_list VALUES(14,'성층권 돌입');
INSERT INTO fke_happening_list VALUES(15,'로켓');
INSERT INTO fke_happening_list VALUES(16,'니논의 폭렬인법');
INSERT INTO fke_happening_list VALUES(17,'슬라이딩');
INSERT INTO fke_happening_list VALUES(18,'순풍');
INSERT INTO fke_happening_list VALUES(19,'드릴');
INSERT INTO fke_happening_list VALUES(20,'기절');
COMMIT;
