PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'notif_data' ('unit_id' INTEGER NOT NULL, 'notif_type' INTEGER NOT NULL, 'comment' TEXT NOT NULL, PRIMARY KEY('unit_id','notif_type'));
INSERT INTO notif_data VALUES(100101,1,'스태미나 완전 회복! 나도 기력 만땅이야! 준비됐으면 모험하러 레츠고~!');
INSERT INTO notif_data VALUES(100101,2,'길드 하우스의 스킵 티켓이 꽉 찼대! 순식간에 해치우자~!');
INSERT INTO notif_data VALUES(100101,3,'기사 군! 길드 하우스의 스태미나가 가득 찼어! 곤란한 사람을 도우려면 체력이 중요하지!');
INSERT INTO notif_data VALUES(100101,4,'길드 하우스의 EXP 포션이 가득이야! 잔뜩 마셔서 더욱더 강해질 거야~!');
INSERT INTO notif_data VALUES(100101,5,'길드 하우스의 마나가 가득 찼어! 어디에 쓸지 고민된다! 기사 군은 벌써 정했어?');
INSERT INTO notif_data VALUES(100101,6,'야호~! 길드 하우스의 아이템이 전부 가득 찼어! …혹시 기사 군, 바빠?');
INSERT INTO notif_data VALUES(100201,1,'기사 군, 스태미나가 완전히 회복됐어. …모험을 떠난다면 나도 데려갔으면 좋겠어');
INSERT INTO notif_data VALUES(100201,2,'길드 하우스의 스킵 티켓가 가득 찼어. 이게 있으면 싸우지 않아도 되니 좋은 거지?');
INSERT INTO notif_data VALUES(100201,3,'길드 하우스의 스태미나가 가득 찼어. …기사 군. 괜찮으면 같이 외출하지 않을래?');
INSERT INTO notif_data VALUES(100201,4,'길드 하우스의 EXP 포션이 가득 찼어. 조금이라도 마법을 잘 썼으면 좋겠다…');
INSERT INTO notif_data VALUES(100201,5,'길드 하우스의 마나가 가득 찼어. 나도 조금은 강해질 수 있을까…?');
INSERT INTO notif_data VALUES(100201,6,'기사 군. 길드 하우스의 아이템이 가득 찼으니… 함께 가지러 가지 않을래?');
INSERT INTO notif_data VALUES(100301,1,'스태미나가 완전히 회복했구나. 강해지려면 실전에서 경험을 쌓는 게 제일이야. 자, 가자!');
INSERT INTO notif_data VALUES(100301,2,'길드 하우스의 스킵 티켓이 가득 찼어. 편하게 적을 쓰러뜨릴 수 있는 건 우리가 강해졌다는 증거지');
INSERT INTO notif_data VALUES(100301,3,'길드 하우스의 스태미나가 가득 찼어. 체력이 남는다면 함께 수행하면 좋겠어');
INSERT INTO notif_data VALUES(100301,4,'길드 하우스의 EXP 포션이 가득 찼어. 자신을 끊임없이 갈고닦는것이 다음 승리의 지름길이야');
INSERT INTO notif_data VALUES(100301,5,'길드 하우스의 마나가 가득 찼어. 이걸로 검술을 더욱 연마할 수 있어. 아직 더 강해질 것 같군');
INSERT INTO notif_data VALUES(100301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 빨리 받도록 해. 알았지?');
INSERT INTO notif_data VALUES(100401,1,'오빠, 스태미나가 전부 회복됐어! 이걸로 미소기랑 놀러갈 수 있겠다!');
INSERT INTO notif_data VALUES(100401,2,'길드 하우스의 스킵 티켓이 꽉 찬 거 같아! 좋았어~ 오빠랑 탐험하러 출발~!');
INSERT INTO notif_data VALUES(100401,3,'길드 하우스의 스태미나가 가득 차 있었어! 빨리 와, 오빠!');
INSERT INTO notif_data VALUES(100401,4,'길드 하우스의 EXP 포션이 가득이야~! 미소기, 오빠보다 클 수 있을지도!?');
INSERT INTO notif_data VALUES(100401,5,'길드 하우스의 마나가 가득이야! 미소기, 새로운 장난 굿즈가 갖고 싶다~');
INSERT INTO notif_data VALUES(100401,6,'길드 하우스의 아이템이 가득이야! 빨리 받지 않으면 미소기가 가질 거야~♪');
INSERT INTO notif_data VALUES(100501,1,'스태미나가 전부 회복했슴다! 이제부터 슈퍼 히어로 타임 시작이네요!');
INSERT INTO notif_data VALUES(100501,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같슴다! 이걸로 모험도 순조롭겠네요!');
INSERT INTO notif_data VALUES(100501,3,'길드 하우스의 스태미나가 가득 찼슴다! 자, 세계의 평화를 지키러 출발임다!');
INSERT INTO notif_data VALUES(100501,4,'길드 하우스의 EXP 포션이 가득 찼슴다! 절대 무적 히어로를 향한 지름길이네요!');
INSERT INTO notif_data VALUES(100501,5,'길드 하우스의 마나가 가득 찼슴다… 히, 히어로 인형 같은 건 안 삽니까!?');
INSERT INTO notif_data VALUES(100501,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼슴다! 회수해서 모험 준비를 하는 검다!');
INSERT INTO notif_data VALUES(100601,1,'스태미나가 회복됐어요. 아카리, 또 오빠랑 하고 싶다~♪');
INSERT INTO notif_data VALUES(100601,2,'길드 하우스의 스킵 티켓이 가득이에요. 아카리랑 함께 가요~ 전투하러♪');
INSERT INTO notif_data VALUES(100601,3,'길드 하우스의 스태미나가 가득 찬 것 같아요. 아카리, 더는 기다릴 수 없어요♪');
INSERT INTO notif_data VALUES(100601,4,'길드 하우스의 EXP 포션이 가득이에요. 아카리, 더욱더 성장할 거예요~♪');
INSERT INTO notif_data VALUES(100601,5,'길드 하우스의 마나가 가득 찼어요~ 아카리, 너무 갖고 싶어요~');
INSERT INTO notif_data VALUES(100601,6,'오빠, 가득 찼어요. 길드 하우스에서 받을 수 있는 아이템이 전부♪');
INSERT INTO notif_data VALUES(100701,1,'스태미나가 전부 회복된 거야~ 빨리 푸딩을 사러 가는 거야~');
INSERT INTO notif_data VALUES(100701,2,'길드 하우스의 스킵 티켓이 가득 찼다! 푸딩 찾기 여행을 떠나는 거야~!');
INSERT INTO notif_data VALUES(100701,3,'길드 하우스의 스태미나가 가득 찬 거야~ 전부 푸딩에 쓰는 거야~');
INSERT INTO notif_data VALUES(100701,4,'길드 하우스의 EXP 포션이 가득 찬 거야~ 푸딩이랑 같이 미야코에게 주는 거야~');
INSERT INTO notif_data VALUES(100701,5,'길드 하우스의 마나가 가득 찬 거야~ ! 이제 푸딩을 잔뜩 살 수 있는 거야~!');
INSERT INTO notif_data VALUES(100701,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찬 거야~ 빨리 받고 미야코에게 푸딩을 받치는 거야!');
INSERT INTO notif_data VALUES(100801,1,'스태미나가 회복된 것 같네. 컨디션 최고인 나… 즉, 완벽한 미모라는 거지!');
INSERT INTO notif_data VALUES(100801,2,'길드 하우스의 스킵 티켓이 가득 찼어. 전투를 스킵하고 나를 유심히 보도록 해♪');
INSERT INTO notif_data VALUES(100801,3,'길드 하우스의 스태미나가 가득 찬 것 같아. 이걸로 아름다운 나를 완전한 상태에서 볼 수 있겠구나♪');
INSERT INTO notif_data VALUES(100801,4,'길드 하우스의 EXP 포션이 가득 찼다고 해. 나의 미모도 더욱 진화할 것 같아♪');
INSERT INTO notif_data VALUES(100801,5,'길드 하우스의 마나가 가득 찼다고 해. 내게 줄 선물을 사는데 써도 좋아♪');
INSERT INTO notif_data VALUES(100801,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찬 것 같아. 그거 전부 나한테 줄 거야?');
INSERT INTO notif_data VALUES(100901,1,'시구르드여, 우리의 스태미나가 전부 회복됐다! 지금이야말로 전진의 때! 이 질풍의 명희가 적을 유린해 주마!');
INSERT INTO notif_data VALUES(100901,2,'우리 근거지의 스킵 티켓 저장고가 한계에 도달했다! 사양 말고 받도록 해라!');
INSERT INTO notif_data VALUES(100901,3,'우리 본거지의 스태미나가 지금이라도 넘칠 것만 같다! 기력을 낭비하지 마라, 시구르드!');
INSERT INTO notif_data VALUES(100901,4,'길드 하우스의 EXP 포션이 보충되었다! 보다 강한 힘을 얻어, 어서 빨리 최강이 되자!');
INSERT INTO notif_data VALUES(100901,5,'우리 길드 하우스의 마나가 가득 찼다!시구르드여, 물론 나에게도 나눠줄 거지?');
INSERT INTO notif_data VALUES(100901,6,'길드 하우스에서 받을 수 있는 아이템이 한계까지 채워졌다! 네가 받지 않겠다면 내가 갖는다?');
INSERT INTO notif_data VALUES(101001,1,'스태미나가 전부 회복된 것 같사옵니다. 함께 외출해요♪');
INSERT INTO notif_data VALUES(101001,2,'길드 하우스의 스킵 티켓이 가득 찼사옵니다. 편해서 좋은 것이 옵니다.');
INSERT INTO notif_data VALUES(101001,3,'길드 하우스의 스태미나가 가득이옵니다. 왕자님만 좋다면 함께 순찰하겠사옵니까?');
INSERT INTO notif_data VALUES(101001,4,'길드 하우스의 EXP 포션이 남았사옵니다. 마시면 마법을 성공하기 쉬워질까요?');
INSERT INTO notif_data VALUES(101001,5,'길드 하우스의 마나가 가득이옵니다. 마나는 보석 같아서 아름답사옵니다♪');
INSERT INTO notif_data VALUES(101001,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼사옵니다. 왕자님은 느긋하시네요♪');
INSERT INTO notif_data VALUES(101101,1,'스태미나가 회복된 것 같아요! 모험 준비는 간단하네요!');
INSERT INTO notif_data VALUES(101101,2,'길드 하우스의 스킵 티켓이 가득 찼어요! 급할수록 돌아가라… 전투를 선회해요!');
INSERT INTO notif_data VALUES(101101,3,'길드 하우스의 스태미나가 가득 찬 것 같아요! 준비가 되면 기쁘다! 맞죠~');
INSERT INTO notif_data VALUES(101101,4,'길드 하우스의 EXP 포션이 가득 찼어요! 좋은 약에 입에 쓰다… 어라? 무슨 뜻이지?');
INSERT INTO notif_data VALUES(101101,5,'길드 하우스의 마나가 가득 찼어요! 돈은 하늘에서 준 선물…이죠!');
INSERT INTO notif_data VALUES(101101,6,'길드 하우스에서 받을 수 있는 아이템이 가득이에요! 이대로 두면 돼지가 홀딱 먹어버릴 거예요!');
INSERT INTO notif_data VALUES(101201,1,'반짝~☆ 스태미나 전부 회복～! 함께 곤란에 처한 사람을 구하러 가자~!');
INSERT INTO notif_data VALUES(101201,2,'와앗! 길드 하우스의 스킵 티켓이 가득 찼어! 낮잠 자기 전에 산책하러 가자~');
INSERT INTO notif_data VALUES(101201,3,'으으! 하츠네, 느껴져! 길드 하우스의 스태미나가… 가득 찼어!');
INSERT INTO notif_data VALUES(101201,4,'길드 하우스의 EXP 포션이 가득이야! 이걸로 내 초능… 마, 마법이 더 강해지겠다!');
INSERT INTO notif_data VALUES(101201,5,'길드 하우스의 마나가 가득이야~! 저기, 저기 나한테도 나눠줘~');
INSERT INTO notif_data VALUES(101201,6,'새근새근… 길드 하우스의 아이템… 전부… 가득… 쿠울');
INSERT INTO notif_data VALUES(101301,1,'스태미나가 전부 회복한 것 같구려! 자, 정기 순회를 합시다!');
INSERT INTO notif_data VALUES(101301,2,'길드 하우스의 스킵 티켓이 가득이네! 좋았어~ 전설의 마도서를 찾으러 가자~');
INSERT INTO notif_data VALUES(101301,3,'길드 하우스의 스태미나가 가득 찼다고!? 이건 마법 소녀로서 움직여야 할 때!?');
INSERT INTO notif_data VALUES(101301,4,'길드 하우스의 EXP 포션이 MAX라고!! 마법 소녀의 성장에는 꼭 필요하지!');
INSERT INTO notif_data VALUES(101301,5,'길드 하우스의 마나가 가득!? 좋았어~ 마도서 잔뜩 사겠어~! …뭐, 안 된다고?');
INSERT INTO notif_data VALUES(101301,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼다고 해! 아이템은 말이지! 빨리 받으라고!');
INSERT INTO notif_data VALUES(101401,1,'스태미나가 전부 회복된 것 같군. 자, 즐거운 추리 시간의 시작이다! 가자, 조수!');
INSERT INTO notif_data VALUES(101401,2,'길드 하우스의 스킵 티켓이 가득 찼구나. 효율적인 추리를 위해 쓰도록 하자!');
INSERT INTO notif_data VALUES(101401,3,'길드 하우스의 스태미나가 가득 찼구나. 조수, 이걸로 오랜 시간 조사해도 문제없어!');
INSERT INTO notif_data VALUES(101401,4,'길드 하우스의 EXP 포션이 가득 찼구나. 레벨을 올려서 난해한 수수께끼에 도전하자!');
INSERT INTO notif_data VALUES(101401,5,'길드 하우스의 마나가 가득 찬 것 같아. 고마워라, 조사 비용으로 쓰도록 하지!');
INSERT INTO notif_data VALUES(101401,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찬 것 같아. 이걸로 추리를 순조롭게 할 수 있어!');
INSERT INTO notif_data VALUES(101501,1,'스태미나가 전부 회복된 것 같네~ 선생님이랑 힘께 놀러 갈까♪');
INSERT INTO notif_data VALUES(101501,2,'어머 어머, 길드 하우스의 스킵 티켓이 가득이네. 너와 여러 곳에 갈 수 있었어~');
INSERT INTO notif_data VALUES(101501,3,'길드 하우스의 스태미나가 가득 찬 것 같아. 자, 그럼 선생님을 어디로 데려가 줄래~?');
INSERT INTO notif_data VALUES(101501,4,'길드 하우스의 EXP 포션이 가득이야. 모두의 성장이 나에게는 가장 큰 행복이야');
INSERT INTO notif_data VALUES(101501,5,'어머! 길드 하우스의 마나가 한가득! 후훗, 낭비하지 않도록 해?');
INSERT INTO notif_data VALUES(101501,6,'길드 하우스에서 받을 수 있는 아이템이 전~부 가득 찬 것 같네~ 잊지 말고 회수하도록 하렴~');
INSERT INTO notif_data VALUES(101601,1,'스태미나가 전부 회복한 것 같아! 텐션 최고다!');
INSERT INTO notif_data VALUES(101601,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같아! 공부 스킵 티켓은 없는 걸까?');
INSERT INTO notif_data VALUES(101601,3,'길드 하우스의 스태미나가 가득이야! 오늘은 파티~ 파티다~☆');
INSERT INTO notif_data VALUES(101601,4,'길드 하우스의 EXP 포션이 가득이래! 이걸로 내 성적도 안 오르려나~');
INSERT INTO notif_data VALUES(101601,5,'길드 하우스의 마나가 가득이야! 둘이서 쇼핑하러 레츠고~!');
INSERT INTO notif_data VALUES(101601,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이래! 자~! 하이 텐션으로 모험하자!');
INSERT INTO notif_data VALUES(101701,1,'안녀~엉! 스태미나도 전부 회복됐고, 나랑 순찰하러 가자~♪');
INSERT INTO notif_data VALUES(101701,2,'길드 하우스의 스킵 티켓이 가득 찼어~ 공수도에도 모험에도 재빠른 움직임은 중요해~!');
INSERT INTO notif_data VALUES(101701,3,'길드 하우스의 스태미나가 가득 찼으니, 같이 춤추고 노래하자~!');
INSERT INTO notif_data VALUES(101701,4,'길드 하우스의 EXP 포션이 가득 찼다고 해~ 이걸 마시면 모두 검은 띠야~!');
INSERT INTO notif_data VALUES(101701,5,'길드 하우스의 마나가 가득 찼어~ 공수도 기술을 연마할 수도 있어~!');
INSERT INTO notif_data VALUES(101701,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어~ 받는 거 도와줄까~?');
INSERT INTO notif_data VALUES(101801,1,'스태미나가 전부 회복한 것 같네. 지금이라면 보충 수업도 잔뜩 할 수 있을 거 같아… 후후, 열심히 하자♪');
INSERT INTO notif_data VALUES(101801,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같아! 하지만 보충 수업은 스킵 할 수 없단다♪');
INSERT INTO notif_data VALUES(101801,3,'길드 하우스의 스태미나가 가득 찬 것 같네. 자, 그럼 수업을 시작할까♪');
INSERT INTO notif_data VALUES(101801,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아. 너도 쑥쑥 성장하겠다~');
INSERT INTO notif_data VALUES(101801,5,'길드 하우스의 마나가 가득이야! 방과 후에 함께 쇼핑이라도 할래?');
INSERT INTO notif_data VALUES(101801,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이야. 완벽한 상태로 열심히 공부하자♪');
INSERT INTO notif_data VALUES(102001,1,'에헤헤, 스태미나 완전 회복~♪ 오빠, 미미랑 놀자?');
INSERT INTO notif_data VALUES(102001,2,'와~ 길드 하우스의 스킵 티켓이 가득이야! 미미는 말이지, 오빠랑 산책하러 가고 싶다~');
INSERT INTO notif_data VALUES(102001,3,'룰루랄라~ 룰루랄라~♪ 길드 하우스의 스태미나 가득~♪ 손잡고 외출하자~?');
INSERT INTO notif_data VALUES(102001,4,'길드 하우스의 EXP 포션이 가득이야! 미미, 언니가 될 수 있을까?');
INSERT INTO notif_data VALUES(102001,5,'음~ 뭐에 쓸까~ 아, 오빠. 길드 하우스의 마나가 가득 찼어~');
INSERT INTO notif_data VALUES(102001,6,'길드 하우스의 아이템을 전부 받을 수 있어~ 굉장하다, 미미도 갖고 싶어~');
INSERT INTO notif_data VALUES(102101,1,'스, 스태미나가 전부 회복한 것 같아요오… 노, 놀아주면 좋겠다…');
INSERT INTO notif_data VALUES(102101,2,'길드 하우스의 스킵 티켓이 가득 찼어요오… 무척 편리하다고 들었는데…');
INSERT INTO notif_data VALUES(102101,3,'길드 하우스의 스태미나가 가득이에요오… 오, 오빠, 모험하러 갈래요…?');
INSERT INTO notif_data VALUES(102101,4,'길드 하우스의 EXP 포션이 가득… 좀 더 요리를 잘 만들 수 있을까…?');
INSERT INTO notif_data VALUES(102101,5,'길드 하우스의 마나가 가득이에요오… 낭비하면 안 돼요…?');
INSERT INTO notif_data VALUES(102101,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어요… …오빠, 인기 많네요…♪');
INSERT INTO notif_data VALUES(102201,1,'스태미나가 전부 회복된 것 같아! 자, 같이 게임을 즐기자!');
INSERT INTO notif_data VALUES(102201,2,'길드 하우스의 스킵 티켓이 가득 찼어! 이제 효율적으로 공략할 수 있겠다!');
INSERT INTO notif_data VALUES(102201,3,'길드 하우스의 스태미나가 가득 찼어! 서둘러 공략하지 않으면 아깝잖아!');
INSERT INTO notif_data VALUES(102201,4,'길드 하우스의 EXP 포션이 가득이야. 성장하면 스테이터스도 올라가! 기대된다~');
INSERT INTO notif_data VALUES(102201,5,'길드 하우스의 마나가 가득이야. 마나를 써서 이것저것 준비하면 모험하기 편해지겠다!');
INSERT INTO notif_data VALUES(102201,6,'길드 하우스에서 받을 수 있는 아이템이 가득이야! 전부 받아서 모험에 활용해 보자!');
INSERT INTO notif_data VALUES(102301,1,'스태미나가 전부 회복됐다고 해! 오빠, 같이 놀자!');
INSERT INTO notif_data VALUES(102301,2,'길드 하우스의 스킵 티켓이 가득이야. 다양한 곳으로 외출할 수 있겠다!');
INSERT INTO notif_data VALUES(102301,3,'길드 하우스의 스태미나가 가득 찼다고 해. 오빠, 같이 탐험하러 가자!');
INSERT INTO notif_data VALUES(102301,4,'길드 하우스의 EXP 포션이 가득 찼어! 마시면 훌륭한 언니가 될 수 있을까…?');
INSERT INTO notif_data VALUES(102301,5,'길드 하우스의 마나가 가득이야! 오빠, 마나는 무척 소중한 거래!');
INSERT INTO notif_data VALUES(102301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼대. 선물이 잔뜩 있어서 좋겠다~!');
INSERT INTO notif_data VALUES(102501,1,'스태미나가 전부 회복됐어요~ 외출하실 거면 같이 가실래요?');
INSERT INTO notif_data VALUES(102501,2,'길드 하우스의 스킵 티켓이 가득이에요. 일도 척척 해낼 수… 있지는 않겠죠?');
INSERT INTO notif_data VALUES(102501,3,'길드 하우스의 스태미나가 가득 찬 거 같아요. 저도 당신을 기다리고 있어요.');
INSERT INTO notif_data VALUES(102501,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아요~ 경험을 쌓으면 덜렁거리는 것도 고쳐질까요!?');
INSERT INTO notif_data VALUES(102501,5,'길드 하우스의 마나가 가득 찬 것 같아요~ 구호원도 이 정도의 여유가 있으면 좋은 생활을…!');
INSERT INTO notif_data VALUES(102501,6,'길드 하우스에서 받을 수 있는 아이템이 가득이네요. 제가 받아둘… 으앗, 소, 손이 미끄러졌어요!');
INSERT INTO notif_data VALUES(102601,1,'스태미나가 전부 회복됐다고 해~ 뭐, 난 움직이지 않을 거지만');
INSERT INTO notif_data VALUES(102601,2,'길드 하우스의 스킵 티켓이 가득 찼다고 해~ 자, 그럼 팥빵 사 와');
INSERT INTO notif_data VALUES(102601,3,'길드 하우스의 스태미나가 가득이야. 나 대신 일 해주라~');
INSERT INTO notif_data VALUES(102601,4,'길드 하우스의 EXP 포션이 쌓였어. 나는 성장해도 계속 게으름 피울 거야');
INSERT INTO notif_data VALUES(102601,5,'길드 하우스의 마나가 가득이래. 게임하고 고급 팥빵 사줘');
INSERT INTO notif_data VALUES(102601,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼습니다… 후우, 공지만 했을 뿐인데 지쳤어');
INSERT INTO notif_data VALUES(102701,1,'스태미나가 전부 회복한 것 같네요. 이걸로 당신에게 다양한 실험을 할 수 있겠어요… 쿡쿡♪');
INSERT INTO notif_data VALUES(102701,2,'길드 하우스의 스킵 티켓이 가득… 전투를 스킵하고 단둘이 느긋하게 지내요');
INSERT INTO notif_data VALUES(102701,3,'길드 하우스의 스태미나가 가득 찬 거 같아요. 체력이 넘치는 당신을… 쿡쿡♪');
INSERT INTO notif_data VALUES(102701,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아요. 약은 좋은 거예요… 쿡쿡♪');
INSERT INTO notif_data VALUES(102701,5,'길드 하우스의 마나가 가득이에요. 당신이 무엇을 살지, 제가 관리할게요');
INSERT INTO notif_data VALUES(102701,6,'길드 하우스의 아이템이 전부 가득… 당신의 것은 나의 것, 당신도 제 것이에요♪');
INSERT INTO notif_data VALUES(102801,1,'어머, 스태미나가 전부 회복됐네. 체력이 남는다면 내 일 좀 도와주지 않을래?');
INSERT INTO notif_data VALUES(102801,2,'길드 하우스의 스킵 티켓이 가득이야, 아까워라. 빨리 받으러 오라고?');
INSERT INTO notif_data VALUES(102801,3,'정말이지, 길드 하우스의 스태미나가 남았잖아. 무슨 일을 하던지 체력은 중요해');
INSERT INTO notif_data VALUES(102801,4,'길드 하우스의 EXP 포션이 가득이네. 경험은 중요해. 성장하기 위해서도 꼭 필요하니까');
INSERT INTO notif_data VALUES(102801,5,'길드 하우스의 마나가 한계까지 쌓였어. 돈도 마나도 돌고 도는 것. 소중히 하라고');
INSERT INTO notif_data VALUES(102801,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이야. 이런 걸 게을리하면 나중에 힘들다고?');
INSERT INTO notif_data VALUES(102901,1,'스태미나가 전부 회복한 것 같으니까, 내 라이브 보러 왔으면 좋겠다♪');
INSERT INTO notif_data VALUES(102901,2,'길드 하우스의 스킵 티켓이 가득 찼어. 레슨도 효율적으로 할 수 있을까?');
INSERT INTO notif_data VALUES(102901,3,'길드 하우스의 스태미나가 가득이네. 함께 외출하고 싶다면 언제든 OK야♪');
INSERT INTO notif_data VALUES(102901,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아. 아이돌로서 더욱 성장할 수 있을지도!');
INSERT INTO notif_data VALUES(102901,5,'길드 하우스의 마나가 가득이네. 괜찮으면 함께 부대 보러 안 갈래?');
INSERT INTO notif_data VALUES(102901,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼네. 많은 선물. 아이돌 같아♪');
INSERT INTO notif_data VALUES(103001,1,'스태미나가 전부 회복입니다! 천하통일 하자입니다!');
INSERT INTO notif_data VALUES(103001,2,'길드 하우스의 스킵 티켓이 가득입니다! 그야말로 인법, 날다람쥐 술법입니다!');
INSERT INTO notif_data VALUES(103001,3,'길드 하우스의 스태미나가 가득입니다! 분명 식량하고 같은 효과가 있다입니다!');
INSERT INTO notif_data VALUES(103001,4,'길드 하우스의 EXP 포션이 가득 찬 것 같습니다! 새로운 인법이 떠오를 것 같다입니다!');
INSERT INTO notif_data VALUES(103001,5,'길드 하우스의 마나가 가득 찬 것 같다요! 잔뜩 모아서 성을 산다입니다!');
INSERT INTO notif_data VALUES(103001,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득입니다! 전부 천하통일 필요한 것이다입니다!');
INSERT INTO notif_data VALUES(103101,1,'스태미나가 전부 회복된 것 같네요. 방황하는 불쌍한 혼을 구제하러 가요');
INSERT INTO notif_data VALUES(103101,2,'길드 하우스의 스킵 티켓이 가득이에요… 하고 당신 뒤에 있는 여자아이가 말했어요');
INSERT INTO notif_data VALUES(103101,3,'길드 하우스의 스태미나가 가득 찬 것 같아요. 제령 의뢰가 들어왔는데, 도와주시겠어요?');
INSERT INTO notif_data VALUES(103101,4,'길드 하우스의 EXP 포션이 가득 찼어요. 어엿한 영매사가 되고 있는 걸까?');
INSERT INTO notif_data VALUES(103101,5,'길드 하우스의 마나가 가득 찼으니까 뭔가 사! …지, 지금 그건 아버지가 한 말이에요');
INSERT INTO notif_data VALUES(103101,6,'제 점에 따르면 길드 하우스에서 받을 수 있는 아이템이 이미 가득 찬 것 같아요…');
INSERT INTO notif_data VALUES(103201,1,'스태미나가 전부 회복한 것 같아요! 시간은 금이라고 하니, 빨리 가보도록 해요!');
INSERT INTO notif_data VALUES(103201,2,'길드 하우스의 스킵 티켓이 가득이네요. 이게 있으면 방향치도 상관없어요!');
INSERT INTO notif_data VALUES(103201,3,'길드 하우스의 스태미나가 가득이네요. 마물 토벌할 때 기사로서 고용해도 되나요?');
INSERT INTO notif_data VALUES(103201,4,'길드 하우스의 EXP 포션이 기득이에요! 분명 상인으로서 경험도 쌓을 수 있을 거예요!');
INSERT INTO notif_data VALUES(103201,5,'길드 하우스의 마나가 가득이에요. 집 한 채 정도는 살 수 있을지 몰라요.');
INSERT INTO notif_data VALUES(103201,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어요. 어머, 집사는 필요 없나요?');
INSERT INTO notif_data VALUES(103301,1,'스태미나가 전부 회복됐어. 자자, 일할 시간이야!');
INSERT INTO notif_data VALUES(103301,2,'길드 하우스의 스킵 티켓이 가득이야! 만담 연습도 효율적으로 할 수 있을까?');
INSERT INTO notif_data VALUES(103301,3,'길드 하우스의 스태미나가 가득 찼어. 목장 일, 열심히 할게!');
INSERT INTO notif_data VALUES(103301,4,'길드 하우스의 EXP 포션이 가득 있었어. 이걸로 모두를 더 많이 웃길 수 있겠어!');
INSERT INTO notif_data VALUES(103301,5,'길드 하우스의 마나가 가득이라고? 마나를 받지 않는 건 매너 위반이야!');
INSERT INTO notif_data VALUES(103301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 뭔가 개그에 쓸 수 있을까?');
INSERT INTO notif_data VALUES(103401,1,'스태미나가 전부 회복한 것 같고… 나, 나를 만나러 와주지 않으려나?');
INSERT INTO notif_data VALUES(103401,2,'길드 하우스의 스킵 티켓이 가득이야. 숙취 시간도 단축되지 않으려나…?');
INSERT INTO notif_data VALUES(103401,3,'기, 길드 하우스의 스태미나가 가득 찬 것 같고… 함께 외출…할래?');
INSERT INTO notif_data VALUES(103401,4,'길드 하우스의 EXP 포션이 가득이야. 설마, 마시면 취하는 건 아니겠지…');
INSERT INTO notif_data VALUES(103401,5,'길드 하우스의 마나가 가득이야. 한잔하러 가자! 너는 주스 마셔♪');
INSERT INTO notif_data VALUES(103401,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이야. 나, 나도 선물 받고 싶은데…?');
INSERT INTO notif_data VALUES(103601,1,'스태미나가 전부 회복되었어요. 알려주지 않으면 잊어버리다니, 어쩔 수 없는 분이네요');
INSERT INTO notif_data VALUES(103601,2,'길드 하우스의 스킵 티켓이 가득이에요. 숙제도 끝냈으니, 함께 외출해요');
INSERT INTO notif_data VALUES(103601,3,'길드 하우스의 스태미나가 가득 찼어요. 이걸로 철봉 테스트도 완벽하겠네요');
INSERT INTO notif_data VALUES(103601,4,'길드 하우스의 EXP 포션이 가득이에요. 흐흥, 금세 성장해서 당신을 따라잡을 거예요!');
INSERT INTO notif_data VALUES(103601,5,'길드 하우스의 마나가 가득이네요. 네? 뭔가 사준다고요? 역시 수상한 사람이네요');
INSERT INTO notif_data VALUES(103601,6,'길드 하우스에서 받을 수 있는 아이템이 가득이에요. 이렇게 쌓아두다니… 확실히 회수하시라고요?');
INSERT INTO notif_data VALUES(103701,1,'스태미나가 전부 회복됐네. 임무를 시작해 볼까');
INSERT INTO notif_data VALUES(103701,2,'길드 하우스의 스킵 티켓이 가득이네. 훈련도 편하게 할 수 있을지도');
INSERT INTO notif_data VALUES(103701,3,'길드 하우스의 스태미나가 가득이네. 그럼 일하러 갈까. 당신도 올 거지?');
INSERT INTO notif_data VALUES(103701,4,'길드 하우스의 EXP 포션이 가득이야. 검술을 더욱 연마해야 해');
INSERT INTO notif_data VALUES(103701,5,'길드 하우스의 마나가 가득 찼어. 자기 수련에 사용해도 좋을 것 같네');
INSERT INTO notif_data VALUES(103701,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 어쩔 수 없네. 기다리고 있을 테니 빨리 와?');
INSERT INTO notif_data VALUES(103801,1,'스태미나가 전부 회복되었어요. 이거라면 조금 멀리 있는 서점에도 갈 수 있을 것 같아요');
INSERT INTO notif_data VALUES(103801,2,'길드 하우스의 스킵 티켓이 가득 찼어요. 몸에 무리 없이 싸울 수 있겠네요');
INSERT INTO notif_data VALUES(103801,3,'길드 하우스의 스태미나가 가득이네요. 체력이 붙으면 저도 모두의 도움이 될 수 있을까요?');
INSERT INTO notif_data VALUES(103801,4,'길드 하우스의 EXP 포션이 가득이에요. 제 몸도 조금은 좋아질까요…');
INSERT INTO notif_data VALUES(103801,5,'길드 하우스의 마나가 가득 찼어요. 이렇게나 있으면 책을 잔뜩 살 수 있겠어요');
INSERT INTO notif_data VALUES(103801,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼어요. 받으면 함께 책 읽어요');
INSERT INTO notif_data VALUES(104001,1,'스태미나가 전부 회복했으니, 친구 사귀러 갑시다…!');
INSERT INTO notif_data VALUES(104001,2,'길드 하우스의 스킵 티켓이 가득이에요… 친구 사귀기에 한발 가까워졌는지도 몰라요!');
INSERT INTO notif_data VALUES(104001,3,'기, 길드 하우스의 스태미나가 가득이네요. 잔뜩 모험을 하면, 친구와 만날 수 있을까요…?');
INSERT INTO notif_data VALUES(104001,4,'길드 하우스의 EXP 포션이 가득이에요. 말솜씨를 좋아지면 친해질까요…?');
INSERT INTO notif_data VALUES(104001,5,'길드 하우스의 마나가 가득이네요. 마나를 주면 친구가 되어줄지도… 어, 안 된다고요?');
INSERT INTO notif_data VALUES(104001,6,'길드 하우스에서 받을 수 있는 아이템이 전부 찼어요. 많은 선물, 부러워요…!');
INSERT INTO notif_data VALUES(104201,1,'스태미나가 모두 회복되었어요. 정령을 위해 노래할 준비는 되어 있어요. …아이돌 노래는 지금부터예요');
INSERT INTO notif_data VALUES(104201,2,'길드 하우스의 스킵 티켓이 가득 찼어요. 사람들을 지키기 위해 힘을 빌려주세요');
INSERT INTO notif_data VALUES(104201,3,'길드 하우스의 스태미나가 가득 찼어요. 노래 연습을 도와줄 수 있으신가요?');
INSERT INTO notif_data VALUES(104201,4,'길드 하우스의 EXP 포션이 가득 찼어요. 목 상태가 나빠지지 않도록…');
INSERT INTO notif_data VALUES(104201,5,'길드 하우스의 마나가 가득 찼어요. 나래나 기술뿐만 아니라, 기재나 장비도 갖추고 싶네요');
INSERT INTO notif_data VALUES(104201,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어요. 노래로 전했어야 했나요?');
INSERT INTO notif_data VALUES(104301,1,'스태미나가 전부 회복한 것 같네. 어이, 외출하자!');
INSERT INTO notif_data VALUES(104301,2,'길드 하우스의 스킵 티켓이 가득 찼다는데. 탐색도 단숨에 끝내버리자고');
INSERT INTO notif_data VALUES(104301,3,'길드 하우스의 스태미나가 가득 찼대. 체력이 남는다면 싸우러 가자!');
INSERT INTO notif_data VALUES(104301,4,'길드 하우스의 EXP 포션이 가득이네. 더욱 강해진 날 보고 싶다고?');
INSERT INTO notif_data VALUES(104301,5,'길드 하우스의 마나가 가득이네. 마음껏 써도 좋지 않아?');
INSERT INTO notif_data VALUES(104301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼다고 해. 전투에 도움 되는 것도 있을 것 같던데?');
INSERT INTO notif_data VALUES(104401,1,'스태미나 전부 회복된 것 같구나. 이몸과 함께 세계 정복을 향해 출진이다!');
INSERT INTO notif_data VALUES(104401,2,'길드 하우스의 스킵 티켓이 가득이구나. 약해빠진 적 따위는 빨리 처리해 버리자!');
INSERT INTO notif_data VALUES(104401,3,'길드 하우스의 스태미나가 회복한 것 같구나. 보급선도 확보되었고, 마음껏 전쟁을 하자꾸나!');
INSERT INTO notif_data VALUES(104401,4,'길드 하우스의 EXP 포션이 가득이구나. 이걸 마시면 어른의 모습으로 돌아가려나…');
INSERT INTO notif_data VALUES(104401,5,'길드 하우스의 마나가 가득이구나. 전쟁에는 군비도 필요하지… 좋은 마음가짐이구나♪');
INSERT INTO notif_data VALUES(104401,6,'길드 하우스의 아이템이 가득 찼구나. 전부 이몸에게 헌상해도 좋다?');
INSERT INTO notif_data VALUES(104501,1,'스태미나가 전부 회복되었어요… 체력이 흘러넘치는 S 씨는 쿠우카에게… 크흐흐…');
INSERT INTO notif_data VALUES(104501,2,'길드 하우스의 스킵 티켓이 가득… 전투를 빨리 끝내고 쿠우카에게 무슨 짓을…?');
INSERT INTO notif_data VALUES(104501,3,'길드 하우스의 스태미나가 가득 찼는데도 받으러 오지 않다니… 애태우는 건가요?');
INSERT INTO notif_data VALUES(104501,4,'길드 하우스의 EXP 포션이 가득이에요. 쿠우카는 이걸로 성장해서 어른의 계단을… 크흐흐…');
INSERT INTO notif_data VALUES(104501,5,'길드 하우스의 마나가 가득… 핫! 서, 설마 쿠우카를 독점하려고 하는 건가요!?');
INSERT INTO notif_data VALUES(104501,6,'길드 하우스의 아이템이 가득이에요… 이걸 사용해서 쿠우카에게 어떤 창피를… 츄릅…');
INSERT INTO notif_data VALUES(104601,1,'스태미나가 회복된 것 같다냥. 시간은 금! 돌아와서 1루피라도 많이 버는 거다냥~');
INSERT INTO notif_data VALUES(104601,2,'길드 하우스의 스킵 티켓이 가득이다냥. 이걸로 아이템을 듬뿍 손에 넣는 거다냥~');
INSERT INTO notif_data VALUES(104601,3,'길드 하우스의 스태미나가 가득 찬 것 같다냥. 전투를 잔뜩해서 보상을 손에 넣는 거다냥~');
INSERT INTO notif_data VALUES(104601,4,'길드 하우스의 EXP 포션이 가득이다냥. 나도 아직 성장 중이니 고마운 일이다냥~');
INSERT INTO notif_data VALUES(104601,5,'길드 하우스의 마나가 가득이다냥. 잔뜩 강해져서 잔뜩 벌어들이는 거냥~');
INSERT INTO notif_data VALUES(104601,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찬 것 같다냥. 빨리 받지 않으면 아깝다냥');
INSERT INTO notif_data VALUES(104701,1,'스태미나가 모두 회복되었다. 전투하기에 충분한 것 같군');
INSERT INTO notif_data VALUES(104701,2,'길드 하우스의 스킵 티켓이 가득 찼다. 임무 수행에는 유용할 것 같다만');
INSERT INTO notif_data VALUES(104701,3,'길드 하우스의 스태미나가 가득이군. 체력이 남아돈다면 훈련을 하는 건 어떤가?');
INSERT INTO notif_data VALUES(104701,4,'길드 하우스의 EXP 포션이 가득이군. 정의를 행하기 위해서는 힘도 필요하다');
INSERT INTO notif_data VALUES(104701,5,'길드 하우스의 마나가 가득 찼다. 자네를 기다리고 있는 동안 동상으로 착각 받고 말았다…');
INSERT INTO notif_data VALUES(104701,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼다. 자네가 받으러 올 때까지 지키고 있겠다');
INSERT INTO notif_data VALUES(104801,1,'스태미나가 전부 회복된 것 같네. 자, 돈 벌러 가자!');
INSERT INTO notif_data VALUES(104801,2,'길드 하우스의 스킵 티켓이 가득 찼어. 효율적으로 사용하자!');
INSERT INTO notif_data VALUES(104801,3,'길드 하우스의 스태미나가 가득 찬 것 같아. 빨리 받고 유용하게 사용하자!');
INSERT INTO notif_data VALUES(104801,4,'길드 하우스의 EXP 포션이 가득이야. 레벨을 올리면 효율도 올라가!');
INSERT INTO notif_data VALUES(104801,5,'길드 하우스의 마나가 가득이야. 효율적인 모험에 사용하도록 하자!');
INSERT INTO notif_data VALUES(104801,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 효율을 올리도록 사용하자!');
INSERT INTO notif_data VALUES(104901,1,'스태미나가 전부 회복됐어~♪ 누나랑 피크닉…이 아니라 모험 가자!');
INSERT INTO notif_data VALUES(104901,2,'길드 하우스의 스킵 티켓이 가득이야~ 이걸로 동생은 위험한 전투를 하지 않아도 돼!');
INSERT INTO notif_data VALUES(104901,3,'길드 하우스의 스태미나가 가득 찼어~! 누나와 함께 모험하러 출발~!');
INSERT INTO notif_data VALUES(104901,4,'길드 하우스의 EXP 포션이 가득이야! 성장한 동생의 모습, 누나는 기대하고 있어!');
INSERT INTO notif_data VALUES(104901,5,'길드 하우스의 마나가 가득이야. 마나를 낭비하지 않도록 누나가 보고 있을게♪');
INSERT INTO notif_data VALUES(104901,6,'길드 하우스의 아이템이 가득! 이거 전부 동생 거! 물론 누나도 동생 거야!');
INSERT INTO notif_data VALUES(105001,1,'스태미나가 전부 회복됐어! 신사답게 날 에스코트해줘!');
INSERT INTO notif_data VALUES(105001,2,'길드 하우스의 스킵 티켓이 가득 찼어. 당연히 근사한 곳에 안내해 줄 거지?');
INSERT INTO notif_data VALUES(105001,3,'봐, 길드 하우스의 스태미나가 가득이잖아! 이런 배려를 할 수 있다니, 난 역시 어른이야');
INSERT INTO notif_data VALUES(105001,4,'길드 하우스의 EXP 포션이 가득 찼어! 더 이상 성장하면 나 어떻게 될까~');
INSERT INTO notif_data VALUES(105001,5,'길드 하우스의 마나가 가득이네! 모처럼이나 세련된 카페라도 데려가 줘!');
INSERT INTO notif_data VALUES(105001,6,'길드 하우스의 아이템이 전부 가득이래! 내가 안 가르쳐줬으면 깜빡했지? 맹하다니까~');
INSERT INTO notif_data VALUES(105101,1,'어머, 스태미나가 전부 회복됐네. 건강해졌다면 또 실험을 도와줄 수 있을까?');
INSERT INTO notif_data VALUES(105101,2,'길드 하우스의 스킵 티켓이 가득이야. 번거로운 건 피하고 싶으니, 활용하도록 하자');
INSERT INTO notif_data VALUES(105101,3,'길드 하우스의 스태미나가 가득이야. 기분 탓인가, 최근 체력이 떨어져서… 지금 한 말은 잊어♪');
INSERT INTO notif_data VALUES(105101,4,'길드 하우스의 EXP 포션이 가득 찼네. 어떤 경험도 성장에 도움이 되지');
INSERT INTO notif_data VALUES(105101,5,'길드 하우스의 마나가 가득 찼네. …물론 나에게 줄 거지?');
INSERT INTO notif_data VALUES(105101,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. …혹시 너, 애태우는 걸 좋아하니?');
INSERT INTO notif_data VALUES(105201,1,'스태미나가 전부 회복했네! 함께 일하자~♪');
INSERT INTO notif_data VALUES(105201,2,'길드 하우스의 스킵 티켓이 가득이야! 일이 무척 편해진다고 해!');
INSERT INTO notif_data VALUES(105201,3,'길드 하우스의 스태미나가 가득 찬 것 같아~ 에헤헤, 잔뜩 수다 떨자♪');
INSERT INTO notif_data VALUES(105201,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아. 어쩌면 인간의 모습으로 변할 수 있을까…?');
INSERT INTO notif_data VALUES(105201,5,'길드 하우스의 마나가 가득이야! 반짝반짝해서 근사하다!');
INSERT INTO notif_data VALUES(105201,6,'길드 하우스에서 받을 수 있는 아이템이 전부 꽉 찼어! 인기인은 좋겠네♪　');
INSERT INTO notif_data VALUES(105301,1,'스태미나가 전부 회복됐군! 쉬고 있을 시간은 없다. 나와 모험을 떠나는 거다!');
INSERT INTO notif_data VALUES(105301,2,'길드 하우스의 스킵 티켓이 가득이다! 효율적으로 모험을 하면 더 강해질 수 있다!');
INSERT INTO notif_data VALUES(105301,3,'길드 하우스의 스태미나가 가득이다! 자, 함께 단련을 시작하자!');
INSERT INTO notif_data VALUES(105301,4,'길드 하우스의 EXP 포션이 가득이다! 조, 조금은 키가 크지 않을까…');
INSERT INTO notif_data VALUES(105301,5,'길드 하우스의 마나가 가득 찼어. 받아둬라. 무슨 일을 하든지 필요할 거다?');
INSERT INTO notif_data VALUES(105301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이군. 쓸만한 것이 잔득 있다');
INSERT INTO notif_data VALUES(105401,1,'기사님! 스태미나가 전부 회복됐어요! 멍하니 있지 말고 빨리 가요!');
INSERT INTO notif_data VALUES(105401,2,'길드 하우스의 스킵 티켓이 가득이에요! 남김없이 쓰도록 해요! …네? 안 된다고요?');
INSERT INTO notif_data VALUES(105401,3,'길드 하우스의 스태미나가 가득 찼어요! 이걸로 의상 만들기도 라이브 운영도 여유롭게 할 수 있겠네요!');
INSERT INTO notif_data VALUES(105401,4,'길드 하우스의 EXP 포션이 가득 찼어요! 봉제 기술을 높여서 이런 옷이나 저런 옷을…!');
INSERT INTO notif_data VALUES(105401,5,'길드 하우스의 마나가 가득이에요! 레이 님에게 선물할 생각인 건… 저요? 아, 안 그러셔도 돼요!');
INSERT INTO notif_data VALUES(105401,6,'길드 하우스에서 받을 수 있는 아이템 전부 다 찼어요! 기사님~? 듣고 있나요~?');
INSERT INTO notif_data VALUES(105501,1,'선배, 스태미나가 전부 회복했어요! …좋았어, 연습은 완벽해…');
INSERT INTO notif_data VALUES(105501,2,'빤히… 길드 하우스의 스킵 티켓이 가득 찼지만, 선배는 알고 있으려나?');
INSERT INTO notif_data VALUES(105501,3,'기, 길드 하우스의 스태미나가… 가득 찼어요! …마, 말했다!');
INSERT INTO notif_data VALUES(105501,4,'길드 하우스의 EXP 포션이 가득 찼다고 선배에게 말하고 싶다…');
INSERT INTO notif_data VALUES(105501,5,'길드 하우스의 마나가 가득 찼어요! 선배는 뭐 하는데 쓸까… 아마, 그거려나?');
INSERT INTO notif_data VALUES(105501,6,'길드 하우스에서 받을 수 있는 아이템이 전부 찼어요… 저, 계속 관찰하고 있었어요');
INSERT INTO notif_data VALUES(105601,1,'이봐, 스태미나가 전부 회복됐다고 해. 손이 모자랄 때는 날 불러. 도와줄 테니까');
INSERT INTO notif_data VALUES(105601,2,'길드 하우스의 스킵 티켓이 가득이야. 편하고 좋네. 낮잠 자도 혼나지 않을 것 같군');
INSERT INTO notif_data VALUES(105601,3,'길드 하우스의 스태미나가 꽉 찼잖아. 한가한 건 좋지만, 종종 몸을 움직여야지');
INSERT INTO notif_data VALUES(105601,4,'길드 하우스의 EXP 포션이 가득 찼어. 네가 강해지라고 말한다면 그렇게 할게');
INSERT INTO notif_data VALUES(105601,5,'길드 하우스의 마나가 가득이야. 그걸 어떻게 사용할지 네 마음대로 해');
INSERT INTO notif_data VALUES(105601,6,'이봐. 길드 하우스에서 받을 수 있는 아이템이 가득 찼어. 가끔은 왕창 거하게 쓰도록 해');
INSERT INTO notif_data VALUES(105701,1,'스태미나가 전부 회복했어! 훌륭한 기공사가 되기 위해 앞으로도 함께 힘내자!');
INSERT INTO notif_data VALUES(105701,2,'길드 하우스의 스킵 티켓이 가득이야! 하늘을 날 수 있다면 여행도 그만큼 쉬워질까?');
INSERT INTO notif_data VALUES(105701,3,'길드 하우스의 스태미나가 가득 찼어! 지금이라면 어떤 의뢰라도 해낼 수 있을 것 같아!');
INSERT INTO notif_data VALUES(105701,4,'길드 하우스의 EXP 포션이 가득이야! 강해져서 아버지 같은 기공사가 될 거야!');
INSERT INTO notif_data VALUES(105701,5,'길드 하우스의 마나가 가득 찼어! 이걸 모아두면 기공선을 살 수 있을까?');
INSERT INTO notif_data VALUES(105701,6,'길드 하우스에서 받을 수 있는 아이템이 가득이야! 다양한 물건 있지만, 전부 소중히 사용하자!');
INSERT INTO notif_data VALUES(105801,1,'스태미나 전부 회복했어요! 하지만 배는 꼬르륵꼬르륵, 밥 먹으러 가요!');
INSERT INTO notif_data VALUES(105801,2,'길드 하우스의 스킵 티켓이 가득이네요~ 밥도 티켓도 남기면 아까워요!');
INSERT INTO notif_data VALUES(105801,3,'스태미나가 남이 돌고 있어요! 저도, 길드 하우스에도!');
INSERT INTO notif_data VALUES(105801,4,'길드 하우스의 EXP 포션이 잔뜩이에요! 자자, 단숨에 마셔 주세요!');
INSERT INTO notif_data VALUES(105801,5,'어라, 길드 하우스의 마나가 남았는데요~! …마나는 먹을 수 있는 건가요?');
INSERT INTO notif_data VALUES(105801,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼네요! 먹을 건 없나요!?');
INSERT INTO notif_data VALUES(105901,1,'스태미나가 전부 회복한 것 같습니다. 외출하신다면 어디든 함께하겠습니다.');
INSERT INTO notif_data VALUES(105901,2,'길드 하우스의 스킵 티켓이 가득입니다. 모험에 사용하는 건 어떠신지요?');
INSERT INTO notif_data VALUES(105901,3,'길드 하우스의 스태미나가 가득입니다. 후후, 주인님은 기운이 넘치시네요.');
INSERT INTO notif_data VALUES(105901,4,'길드 하우스의 EXP 포션이 가득입니다. 주인님을 지키기 위해서도 성장하지 않으면…!');
INSERT INTO notif_data VALUES(105901,5,'길드 하우스의 마나가 가득입니다. 이렇게나 모으실 줄이야, 역시 주인님이시네요…♪');
INSERT INTO notif_data VALUES(105901,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼습니다. 열심히 노력하셨네요, 주인님.');
INSERT INTO notif_data VALUES(106001,1,'스태미나가 다 회복됐네. 뭐 하고 있어. 빨리 모험하러 가자고?');
INSERT INTO notif_data VALUES(106001,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같네. 외출할 거면 받아두라고.');
INSERT INTO notif_data VALUES(106001,3,'길드 하우스의 스태미나도 가득 찼으니, 탐색하러 가자. 자, 날 따라와!');
INSERT INTO notif_data VALUES(106001,4,'길드 하우스의 EXP 포션이 가득이야. 나 좀 더 강해지겠다♪');
INSERT INTO notif_data VALUES(106001,5,'길드 하우스의 마나가 가득이야. 여러모로 쓸모 있으니, 가지고 있으면 손해는 안 볼걸?');
INSERT INTO notif_data VALUES(106001,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼네. 받으며 모험 준비를 하도록 해!');
INSERT INTO notif_data VALUES(106101,1,'스태미나도 전부 회복됐으니 모험을 떠나자! 빨리 준비하지 않으면 두고 갈 거다!');
INSERT INTO notif_data VALUES(106101,2,'길드 하우스의 스킵 티켓이 가득이야! 귀찮은 일은 재빨리 끝내고, 크레이프라도 먹으러 가자!');
INSERT INTO notif_data VALUES(106101,3,'길드 하우스의 스태미나가 가득 찼네! 이만큼이나 있으면 마음껏 할 수 있겠어! …그렇지도 않다고?');
INSERT INTO notif_data VALUES(106101,4,'길드 하우스의 EXP 포션이 가득이야! 쓰지 않을 거면 조금 정도는 나눠줄래?');
INSERT INTO notif_data VALUES(106101,5,'길드 하우스의 마나가 가득이야! 이걸로 조금은 키가 크면 좋겠는데~ …시험 삼아 해볼까!');
INSERT INTO notif_data VALUES(106101,6,'길드 하우스에서 받을 수 있는 아이템이 가득이라고! 바쁘면 내가 받아 둘게! …당연히 제대로 건네줄 거야!');
INSERT INTO notif_data VALUES(106301,1,'스태미나가 전부 회복했어! 좋았어~ 로자리아를 찾으러 가자!');
INSERT INTO notif_data VALUES(106301,2,'길드 하우스의 스킵 티켓이 가득 찼어! 랜드솔 외각에 데려갔으면 좋겠다');
INSERT INTO notif_data VALUES(106301,3,'길드 하우스의 스태미나가 가득 찼대! 숲의 수호자 훈련 좀 도와줘!');
INSERT INTO notif_data VALUES(106301,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아! 이걸로 어엿한 숲의 수호자에 다가갔을까?');
INSERT INTO notif_data VALUES(106301,5,'길드 하우스의 마나가 가득이네! 마침 화살이 거의 다 떨어졌었어~');
INSERT INTO notif_data VALUES(106301,6,'길드 하우스에서 받을 수 있는 아이템이 가득이야! 빨리 회수하지 않으면 아까워~!');
INSERT INTO notif_data VALUES(107101,1,'스태미나라는 것이 회복된 것 같군. 유쾌한 일이 있다면 조금은 어울려 줄 수 있는데?');
INSERT INTO notif_data VALUES(107101,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같군. 즐거운 전투를 스킵 하다니, 나는 도저히 이해할 수 없지만…');
INSERT INTO notif_data VALUES(107101,3,'길드 하우스의 스태미나가 가득 찬 것 같군. 이게 있으면 살을 베는 감촉을 맛볼 수 있는 건가?');
INSERT INTO notif_data VALUES(107101,4,'길드 하우스의 EXP 포션이 가득 찬 것 같군. 흥, 내가 더욱 강해지면 어떻게 돼도 모른다?');
INSERT INTO notif_data VALUES(107101,5,'길드 하우스의 마나가 가득이군. 네가 준다고 한다면, 뭐~ 내 멋대로 사용해 주마');
INSERT INTO notif_data VALUES(107101,6,'길드 하우스에서 받을 수 있는 아이템이 한가득이다. 전부 네 것이다. 빨리 받도록 해라.');
INSERT INTO notif_data VALUES(107501,1,'스태미나가 전부 회복됐어요~☆ 이제 헤엄치러 갈 수 있겠네요!');
INSERT INTO notif_data VALUES(107501,2,'길드 하우스의 스킵 티켓이 가득이에요! 좋았어~ 해산물을 잡으러 가요!');
INSERT INTO notif_data VALUES(107501,3,'길드 하우스의 스태미나가 가득이에요! 바다까지 경주해요!');
INSERT INTO notif_data VALUES(107501,4,'길드 하우스의 EXP 포션이 가득이에요♪ 더 이상 성장하면, 수영복이… 장난 아니네요!');
INSERT INTO notif_data VALUES(107501,5,'길드 하우스의 마나가 가득 찼어요! 저 남쪽 나라의 과일이 먹고 싶어요!');
INSERT INTO notif_data VALUES(107501,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이에요! 장난 아니네요☆');
INSERT INTO notif_data VALUES(107601,1,'스태미나가 모두 회복되었습니다. 바다에서 주인님을 기다리고 있겠습니다');
INSERT INTO notif_data VALUES(107601,2,'길드 하우스의 스킵 티켓이 가득 찬 듯합니다. 주인님과 단둘이 조금 먼 곳에 가보고 싶습니다');
INSERT INTO notif_data VALUES(107601,3,'길드 하우스의 스태미나가 가득 찼습니다. 함께 수영 연습을 하도록 하죠');
INSERT INTO notif_data VALUES(107601,4,'길드 하우스의 EXP 포션이 가득입니다. 저, 커질 수 있을까요? 여러모로…');
INSERT INTO notif_data VALUES(107601,5,'길드 하우스의 마나가 가득입니다. 가끔은 사치를 부리는 것도 좋을지 모르겠네요♪');
INSERT INTO notif_data VALUES(107601,6,'길드 하우스에서 받을 수 있는 아이템이 가득입니다. 저도 받는 걸 도와드리겠습니다♪');
INSERT INTO notif_data VALUES(107701,1,'아! 스태미나가 철퍼덕!… 스, 스태미나가 전부 회복됐어요…');
INSERT INTO notif_data VALUES(107701,2,'길드 하우스의 스킵 티켓이 가득 찼어요! 저도 바다에서 놀고 싶네요');
INSERT INTO notif_data VALUES(107701,3,'길드 하우스의 스태미나가 가득 찼습니다! 수영복을 입었어도 열심히 봉사할게요!');
INSERT INTO notif_data VALUES(107701,4,'길드 하우스의 EXP 포션이 가득 찼어요! 이걸로 실수투성이 메이드를 졸업할 거예요!');
INSERT INTO notif_data VALUES(107701,5,'길드 하우스의 마나가 가득 찬 거 같네요! 바다의 집에서 기다리고 있을게요♪');
INSERT INTO notif_data VALUES(107701,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼어요! 제가 받아둘까요? …네? 불안하다고요?');
INSERT INTO notif_data VALUES(107801,1,'이봐, 스태미나가 전부 회복됐잖아! 빨리 돌아오라고!');
INSERT INTO notif_data VALUES(107801,2,'길드 하우스의 스킵 티켓이 가득이야! 빨리 날 바다에 데려가도록 해!');
INSERT INTO notif_data VALUES(107801,3,'길드 하우스의 스태미나가 가득이잖아! 자, 바캉스 가자!');
INSERT INTO notif_data VALUES(107801,4,'길드 하우스의 EXP 포션이 가득이야! 나, 더욱 강해질지도!');
INSERT INTO notif_data VALUES(107801,5,'길드 하우스의 마나가 가득이네. 사용할 곳을 생각해 뒀어?');
INSERT INTO notif_data VALUES(107801,6,'길드 하우스에서 받을 수 있는 아이템이 가득이야. 넌 잘 잊으니까 내가 가르쳐줄게');
INSERT INTO notif_data VALUES(107901,1,'스태미나를 회복한 것 같다냥. 내 수영복 차림을 보고 싶다면 빨리 오는 거냥~');
INSERT INTO notif_data VALUES(107901,2,'길드 하우스의 스킵 티켓이 가득 찼다냥! 이걸로 신기한 아이템을 손에 넣는거냥~');
INSERT INTO notif_data VALUES(107901,3,'길드 하우스의 스태미나가 가득 찬 것 같다냥. 너도 내가 만든 붕어빵을 먹고 스태미나를 채우는 거냥!');
INSERT INTO notif_data VALUES(107901,4,'길드 하우스의 EXP 포션이 가득이다냥. 당장 여름 모험으로 출발하는 거냥~!');
INSERT INTO notif_data VALUES(107901,5,'길드 하우스의 마나가 가득 찼다냥. 이걸로 여름 마물도 잔뜩 퇴치할 수 있다냥~!');
INSERT INTO notif_data VALUES(107901,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찬 것 같다냥. 빨리 오지 않으면 내가 가질 거다냥~');
INSERT INTO notif_data VALUES(108001,1,'스태미나가 전부 회복됐네. 바다의 모험은 체력 승부니까, 고마운 일이야!');
INSERT INTO notif_data VALUES(108001,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같아. 여름 바다로 떠나자!');
INSERT INTO notif_data VALUES(108001,3,'길드 하우스의 스태미나가 가득 찼어. 더위도 모른 채 모험을 할 수 있겠어!');
INSERT INTO notif_data VALUES(108001,4,'길드 하우스의 EXP 포션이 가득 찼네. 자, 레벨을 올리고 바다를 제압하자!');
INSERT INTO notif_data VALUES(108001,5,'길드 하우스의 마나가 가득 찬 것 같아. 여름 모험에 요긴하게 쓰자!');
INSERT INTO notif_data VALUES(108001,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 바다에서의 효율을 최고로 높이자~!');
INSERT INTO notif_data VALUES(108101,1,'스태미나가 전부 회복되었어요… 아버지가 할로윈 코스프레 의상을 입은 여자아이를 보러 밖에 나가자고 하네요');
INSERT INTO notif_data VALUES(108101,2,'길드 하우스의 스킵 티켓이 가득 찼어요… 할로윈 모험에 유용하게 써 주세요');
INSERT INTO notif_data VALUES(108101,3,'길드 하우스의 스태미나가 가득 찼네요. 그럼 할로윈 파티를 시작하죠');
INSERT INTO notif_data VALUES(108101,4,'길드 하우스의 EXP 포션이 가득 찼어요… 이걸로 할로윈 악령을 퇴치할 수 있겠네요');
INSERT INTO notif_data VALUES(108101,5,'길드 하우스의 마나가 가득이네요. 할로윈 때 나눠 줄 과자를 사러 가지 않을래요?');
INSERT INTO notif_data VALUES(108101,6,'길드 하우스에서 받을 수 있는 아이템이 가득이에요. 할로윈 모험을 시작하실래요?');
INSERT INTO notif_data VALUES(108201,1,'스태미나가 전부 회복된 거야! 할로윈 한정 푸딩을 사러 가는 거야~');
INSERT INTO notif_data VALUES(108201,2,'트릭 오어 푸딩~♪길드 하우스의 스킵 티켓이 가득 찬 거야~');
INSERT INTO notif_data VALUES(108201,3,'길드 하우스의 스태미나가 가득 찬 거야! 빨리 할로윈 파티에 가는 거야!');
INSERT INTO notif_data VALUES(108201,4,'길드 하우스의 EXP 포션이 가득인 거야. 괴롭힘당하기 싫으면 빨리 받는 거야!');
INSERT INTO notif_data VALUES(108201,5,'길드 하우스의 마나가 가득 찬 거야~ 이걸로 푸딩이랑 과자를 잔뜩 사는 거야!');
INSERT INTO notif_data VALUES(108201,6,'길드 하우스에서 받을 수 있는 아이템이 가득인 거야! 빨리 받고 할로윈 파티하는 거야!');
INSERT INTO notif_data VALUES(108301,1,'스태미나가 전부 회복됐어. 할로윈 거리로 나가보자!');
INSERT INTO notif_data VALUES(108301,2,'길드 하우스의 스킵 티켓이 가득이야! 자, 데이트하러 밖으로 나를 데려가');
INSERT INTO notif_data VALUES(108301,3,'길드 하우스의 스태미나가 가득이네. 과자를 받으러 가자. 네가 먹고 싶어 하는 것 같으니까');
INSERT INTO notif_data VALUES(108301,4,'길드 하우스의 EXP 포션이 가득이네! 성장해서 마성의 여자가 되겠어♪');
INSERT INTO notif_data VALUES(108301,5,'길드 하우스의 마나가 가득이잖아! …왜 그래? 딱히 들뜨지 않았어!');
INSERT INTO notif_data VALUES(108301,6,'길드 하우스에서 받을 수 있는 아이템이 가득이야! 과자도 이것도 잊지 말고 받도록 해!');
INSERT INTO notif_data VALUES(108401,1,'스태미나가 전부 회복되었네요. 이걸로 성탄절 스테이지에서 끝까지 해낼 수 있을 거 같아요… 들어주세요');
INSERT INTO notif_data VALUES(108401,2,'길드 하우스의 스킵 티켓이 가득 찼어요. 성탄절 선물, 소중히 사용해요!');
INSERT INTO notif_data VALUES(108401,3,'길드 하우스의 스태미나가 가득 찼어요. 산타클로스가 주는 선물일까요?');
INSERT INTO notif_data VALUES(108401,4,'길드 하우스의 EXP 포션이 가득 찼네요. 이걸로 더욱 근사한 성가를 부를 수 있을지도…');
INSERT INTO notif_data VALUES(108401,5,'길드 하우스의 마나가 가득 찼네요. 후후, 크리스마스 파티를 할까요?');
INSERT INTO notif_data VALUES(108401,6,'길드 하우스에서 받을 수 있는 아이템이 가득이네요. 성탄절 모험에 유용하게 써요!');
INSERT INTO notif_data VALUES(108501,1,'스태미나가 전부 회복된 것 같아요… 오, 오빠, 크리스마스 마을을 함께 걷지 않을래요…?');
INSERT INTO notif_data VALUES(108501,2,'길드 하우스의 스킵 티켓이 가득이에요… 이 티켓으로 크리스마스 무대를 볼 수 있었으면 좋겠다…♪');
INSERT INTO notif_data VALUES(108501,3,'길드 하우스의 스태미나가 가득이에요… 저기… 괜찮으면 연기 연습을 도와주시겠어요…?');
INSERT INTO notif_data VALUES(108501,4,'길드 하우스의 EXP 포션이 가득… 성장하면 낯가림이나 말솜씨가 없는 것도 고쳐질까…?');
INSERT INTO notif_data VALUES(108501,5,'길드 하우스의 마나가 가득… 크리스마스니까, 조금은 낭비해도 잠자코 있어 줄게요♪');
INSERT INTO notif_data VALUES(108501,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득… 분명 오빠에게 주는 크리스마스 선물일 거예요…♪');
INSERT INTO notif_data VALUES(108601,1,'스태미나 완전 회복～♪ 오빠, 함께 크리스마스 장 보러 가자~!');
INSERT INTO notif_data VALUES(108601,2,'길드 하우스의 스킵 티켓이 가득이야! 넓은 광장에 가서 눈사람 만들고 싶다~♪');
INSERT INTO notif_data VALUES(108601,3,'길드 하우스의 스태미나가 가득이야! 당장 크리스마스 파티를 시작하자~♪');
INSERT INTO notif_data VALUES(108601,4,'길드 하우스의 EXP 포션이 잔뜩! 푸우키치가 마시면 성장해서 커질까?');
INSERT INTO notif_data VALUES(108601,5,'길드 하우스의 마나가 가득이야! 이렇게나 있으면 커다란 칠면조도 달콤한 케이크도 마음껏 먹을 수 있겠다♪');
INSERT INTO notif_data VALUES(108601,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득이야! 받지 않으면 푸우키치 산타가 아이들한테 나눠줄걸♪');
INSERT INTO notif_data VALUES(108801,1,'스태미나가 전부 회복된 것 같아. 저, 저기 기사 군… 같이 새해 참배하러 가고 싶은데… 안 될까?');
INSERT INTO notif_data VALUES(108801,2,'길드 하우스의 스킵 티켓이 잔뜩. 밖에 나간다면 첫 일출이 아름답게 보이는 곳이 좋겠어…');
INSERT INTO notif_data VALUES(108801,3,'길드 하우스의 스태미나가 가득이야. 새해 떡을 준비해야지…기사 군도 와주면 기쁠 거야');
INSERT INTO notif_data VALUES(108801,4,'길드 하우스의 EXP 포션이 가득이네. 나도 강해져서 내 마음을 전할 만큼의 용기가 있었으면 좋겠어…');
INSERT INTO notif_data VALUES(108801,5,'길드 하우스의 마나가 가득 찬 것 같아. 새해 쇼핑은… 복주머니가 어때?');
INSERT INTO notif_data VALUES(108801,6,'길드 하우스의 아이템이 한가득. 새해는 바쁘지. 저기… 여기에는 새해 음식도 있고, 느긋하게 지낼 수 있을 텐데…');
INSERT INTO notif_data VALUES(108901,1,'스태미나가 전부 회복된 것 같네. 새해라고 해서 게으름 피우는 건 금물이야. 함께 특훈하자!');
INSERT INTO notif_data VALUES(108901,2,'길드 하우스의 스킵 티켓이 가득이군. 수업을 일찍 끝내고 새해의 거리를 여유롭게 걷는 것도 좋겠다.');
INSERT INTO notif_data VALUES(108901,3,'길드 하우스의 스태미나가 가득이네. 이 시기에만 할 수 있는 눈 위의 전투 훈련을 해 볼까?');
INSERT INTO notif_data VALUES(108901,4,'길드 하우스의 EXP 포션이 가득이네. 힘을 위한 탐구는 어떤 때도 해야 해. 설령 그게 새해라 해도 말이야.');
INSERT INTO notif_data VALUES(108901,5,'길드 하우스의 마나가 가득 찼어. 이렇게나 있다면 새해 할인 매장에 간다거나… 저기… 난 오늘 일정이 비어있는데?');
INSERT INTO notif_data VALUES(108901,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 새해라고 멍하니 있지 말고 받으러 와… 나도 기다리고 있으니까');
INSERT INTO notif_data VALUES(108701,1,'스태미나가 전부 회복됐어! 새해이기도 하고 같이 하네츠키하자! 기사 군을 먹물투성이로 만들어 줄 테니까♪');
INSERT INTO notif_data VALUES(108701,2,'길드 하우스의 스킵 티켓이 잔뜩! 저기 저기, 밖에서 연날리기 하자! 누가 높게 띄울지 경쟁하는 거야!');
INSERT INTO notif_data VALUES(108701,3,'길드 하우스의 스태미나가 가득이야! 집안에서 할 수 있는 일… 아, 모두를 불러서 카루타 놀이하자~♪');
INSERT INTO notif_data VALUES(108701,4,'길드 하우스의 EXP 포션이 가득이야! 더 강해져서 많은 사람을 도울 수 있게 되면 좋겠어!');
INSERT INTO notif_data VALUES(108701,5,'길드 하우스의 마나가 가득이야! 저기 저기, 어디에 쓸 거야? 난 노점의 오징어구이를 추천해♪');
INSERT INTO notif_data VALUES(108701,6,'길드 하우스의 아이템이 전부 찼어! 내가 정리해서… 어라? 어쩐지 무너지는 것 같은… 기, 기사 군! 빨리 받으러 와!');
INSERT INTO notif_data VALUES(109001,1,'스태미나가 전부 회복됐어요. 녹을 듯한 발렌타인, 저와 영원히 함께 지내요…');
INSERT INTO notif_data VALUES(109001,2,'길드 하우스의 스킵 티켓이 가득이네요… 초콜릿 재료 모으기에 도움 될 것 같네요');
INSERT INTO notif_data VALUES(109001,3,'길드 하우스의 스태미나가 가득… 쿡쿡. 외출하신다면 따라갈게요… 끝까지');
INSERT INTO notif_data VALUES(109001,4,'길드 하우스의 EXP 포션이 가득 찼어요… 초콜릿에 섞어서… 농담이에요. 쿡쿡…');
INSERT INTO notif_data VALUES(109001,5,'길드 하우스의 마나가 가득 찼어요. 더욱 강해져서 더욱 좋은 재료를 손에 넣겠어요');
INSERT INTO notif_data VALUES(109001,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼어요… 당신이 받으러 올 때를 기다리고 있어요… 언제까지라도… 쿡쿡');
INSERT INTO notif_data VALUES(109101,1,'스태미나 완전 회복이야! 발렌타인은 누나와 함께 달콤한 시간을 보내자♪');
INSERT INTO notif_data VALUES(109101,2,'길드 하우스의 스킵 티켓이 가득이네! 발렌타인도 모험하러 갈까? 물론 누나도 같이 가 줄게♪');
INSERT INTO notif_data VALUES(109101,3,'길드 하우스의 스태미나가 가득 찼어! 달콤~한 하루, 누나랑 함께 잔뜩 외출하자♪');
INSERT INTO notif_data VALUES(109101,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아! 누나도 더욱 강해질게♪');
INSERT INTO notif_data VALUES(109101,5,'길드 하우스의 마나가 가득이야~ 어디에 쓸지, 누나가 관리해 줄까?');
INSERT INTO notif_data VALUES(109101,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼네! 누나랑 같이 정리할까. 잘 정리하면 많이 칭찬해 줄게♪');
INSERT INTO notif_data VALUES(109201,1,'스태미나가 전부 회복됐다고 해! 자, 출발하자!');
INSERT INTO notif_data VALUES(109201,2,'길드 하우스의 스킵 티켓이 가득 찼어! 여기야 여기, 빨리~!');
INSERT INTO notif_data VALUES(109201,3,'길드 하우스의 스태미나가 가득이야! 좋았어, 힘내자~!');
INSERT INTO notif_data VALUES(109201,4,'길드 하우스의 EXP 포션이 가득 찼어! 모험에 요긴하게 쓰자!');
INSERT INTO notif_data VALUES(109201,5,'길드 하우스의 마나가 가득 찼어! 소중히 사용하자!');
INSERT INTO notif_data VALUES(109201,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찬 것 같아!');
INSERT INTO notif_data VALUES(109301,1,'스태미나가 전부 회복됐어요~! 같이 놀러 가는 거예요~!');
INSERT INTO notif_data VALUES(109301,2,'길드 하우스의 스킵 티켓이 가득 찼어요! 즐겁게 청춘을 만끽하는 거예요~!');
INSERT INTO notif_data VALUES(109301,3,'길드 하우스의 스태미나가 가득이에요! 이걸로 잔뜩 놀 수 있겠네요!');
INSERT INTO notif_data VALUES(109301,4,'길드 하우스의 EXP 포션이 가득이에요~! 당장 사용해요!');
INSERT INTO notif_data VALUES(109301,5,'길드 하우스의 마나가 가득 찼어요! 루는 과자가 먹고 싶어요~!');
INSERT INTO notif_data VALUES(109301,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어요~!');
INSERT INTO notif_data VALUES(109401,1,'스태미나가 전부 회복됐어. 그럼 모험을 떠날까');
INSERT INTO notif_data VALUES(109401,2,'길드 하우스의 스킵 티켓이 가득 찼어. 보러 오는 편이 좋을지도…');
INSERT INTO notif_data VALUES(109401,3,'길드 하우스의 스태미나가 가득 찼어. 슬슬 외출 안 할래…?');
INSERT INTO notif_data VALUES(109401,4,'길드 하우스의 EXP 포션이 가득 찼네. 더욱 강해질 수 있을까…');
INSERT INTO notif_data VALUES(109401,5,'길드 하우스의 마나가 가득 찼네. 과소비는 주의해야 해…');
INSERT INTO notif_data VALUES(109401,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어');
INSERT INTO notif_data VALUES(109501,1,'스태미나가 전부 회복된 것 같네요… 앗! 설마 흘러넘치는 체력으로 쿠우카의 허리띠를…!?');
INSERT INTO notif_data VALUES(109501,2,'길드 하우스의 스킵 티켓이 가득이에요…! 전투를 빠르게 끝내고 쿠우카의 옷을 천천히…!?');
INSERT INTO notif_data VALUES(109501,3,'길드 하우스의 스태미나가 가득이에요! 단번에 사용해서 쿠우카를 못 쉬게 할 생각인 거죠!?');
INSERT INTO notif_data VALUES(109501,4,'길드 하우스의 EXP 포션이 가득 찼어요… 쿠우카를 성장시켜 더 다양한 짓을…!?');
INSERT INTO notif_data VALUES(109501,5,'길드 하우스의 마나가 가득이에요…! 아, 안 돼요 S 씨. 쿠우카를 원한다니… 크흐흐');
INSERT INTO notif_data VALUES(109501,6,'길드 하우스의 아이템이 가득이에요…! 쿠우카도 함께 받아주는 거네요… 츄릅…!');
INSERT INTO notif_data VALUES(109601,1,'스태미나가 전부 회복입니다! 몰래 외출하자입니다!');
INSERT INTO notif_data VALUES(109601,2,'길드 하우스의 스킵 티켓이 가득입니다! 쇼군과 천하통일을 목표로 슈라슈슈슈~입니다!');
INSERT INTO notif_data VALUES(109601,3,'길드 하우스의 스태미나가 가득입니다! 즐거움은 지금부터입니다!');
INSERT INTO notif_data VALUES(109601,4,'길드 하우스의 EXP 포션이 가득입니다! 인법을 더 갈고닦아 무적의 닌자가 된다입니다!');
INSERT INTO notif_data VALUES(109601,5,'길드 하우스의 마나가 가득입니다! 이걸로 통일 전투도 유리해지겠다입니다!');
INSERT INTO notif_data VALUES(109601,6,'길드 하우스에서 받을 수 있는 아이템이 가득입니다! 백만 석이 쌓일 기세입니다!');
INSERT INTO notif_data VALUES(109701,1,'스태미나가 전부 회복된 것 같아요. 모험을 떠날까요?');
INSERT INTO notif_data VALUES(109701,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같아요. 받아두도록 해요');
INSERT INTO notif_data VALUES(109701,3,'길드 하우스의 스태미나가 가득 찬 것 같아요. 받아두도록 해요');
INSERT INTO notif_data VALUES(109701,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아요. 렘에게 사용해도 되나요?');
INSERT INTO notif_data VALUES(109701,5,'길드 하우스의 마나가 가득 찬 것 같아요. 이 세계의 마나는 신기하네요');
INSERT INTO notif_data VALUES(109701,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찬 것 같아요. 렘이 정리해버리기 전에 회수해 주세요');
INSERT INTO notif_data VALUES(109801,1,'스태미나가 전부 회복된 것 같네. 람이 따라갔으면 좋겠어? 어쩔 수 없네. 감사하도록 해');
INSERT INTO notif_data VALUES(109801,2,'길드 하우스의 스킵 티켓이 가득이야. 전투를 빠르게 끝낼 수 있는 건 좋지');
INSERT INTO notif_data VALUES(109801,3,'길드 하우스의 스태미나가 가득 찼어. 자, 람 대신 힘내');
INSERT INTO notif_data VALUES(109801,4,'길드 하우스의 EXP 포션이 가득이네. 힘을 원하는 건 당연한 거야. 열심히 노력하도록 해');
INSERT INTO notif_data VALUES(109801,5,'길드 하우스의 마나가 가득 찼어. 최소한 쓸 곳은 신중히 정해');
INSERT INTO notif_data VALUES(109801,6,'길드 하우스의 아이템이 가득 찼다고 해. 람한테 정리하라는 거야? 뭐, 귀찮지만 해 줄게');
INSERT INTO notif_data VALUES(109901,1,'스태미나가 전부 회복된 것 같아! 있잖아, 어딘가 가보지 않을래?');
INSERT INTO notif_data VALUES(109901,2,'길드 하우스의 스킵 티켓이 가득이네! 무척 편리할 것 같으니 받아야지!');
INSERT INTO notif_data VALUES(109901,3,'길드 하우스의 스태미나가 가득이야! 쓸모 없어지기 전에 받아두자?');
INSERT INTO notif_data VALUES(109901,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아. 있잖아, 빨리 받아둬');
INSERT INTO notif_data VALUES(109901,5,'길드 하우스의 마나가 가득! 이렇게 마나가 있으면 팩도 기뻐할까?');
INSERT INTO notif_data VALUES(109901,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어. 이렇게나 있으니 다양한 걸 할 수 있을 것 같아');
INSERT INTO notif_data VALUES(110001,1,'스태미나가 전부 회복됐어! 파도가 히데사이를 기다리고 있어!');
INSERT INTO notif_data VALUES(110001,2,'길드 하우스의 스킵 티켓이 가득이야! 편리하니까 당연히 써야겠지?');
INSERT INTO notif_data VALUES(110001,3,'길드 하우스의 스태미나가 가득이래! 빨리 받으러 가자!');
INSERT INTO notif_data VALUES(110001,4,'길드 하우스의 EXP 포션이 가득이래! 이게 있으면 더 귀여워지겠네!');
INSERT INTO notif_data VALUES(110001,5,'길드 하우스의 마나가 가득 찬 거 같아! 안 받으면 화낼 거야!');
INSERT INTO notif_data VALUES(110001,6,'길드 하우스가 아이템으로 가득 찼어~! 길드 하우스가 빵빵~! 엄청 웃긴다!');
INSERT INTO notif_data VALUES(110101,1,'스태미나가 전부 회복됐어! 지금만큼은 숙제 같은 건 잊고 마음껏 바캉스를 즐기자!');
INSERT INTO notif_data VALUES(110101,2,'길드 하우스의 스킵 티켓이 가득이야! 이걸로 여름 바다도 100점 만점!');
INSERT INTO notif_data VALUES(110101,3,'길드 하우스의 스태미나가 가득이야. 수영 연습, 같이 하지 않을래?');
INSERT INTO notif_data VALUES(110101,4,'길드 하우스의 EXP 포션이 가득이야. 이걸로 헤엄칠 수 있게 될지도~?');
INSERT INTO notif_data VALUES(110101,5,'길드 하우스의 마나가 가득 찼어. 바다의 집에서 같이 뭔가 먹지 않을래?');
INSERT INTO notif_data VALUES(110101,6,'길드 하우스에서 받을 수 있는 아이템이 전부 가득 찼어! 해변에서 놀 수 있을 만한 물건은 없는지, 봐 보자?');
INSERT INTO notif_data VALUES(110301,1,'스태미나가 전부 회복된 것 같아. 기운 있으면 헤엄치지 않을래?');
INSERT INTO notif_data VALUES(110301,2,'길드 하우스의 스킵 티켓이 가득 찬 것 같아. 받지 않으면 아까워');
INSERT INTO notif_data VALUES(110301,3,'길드 하우스의 스태미나가 가득 찬 것 같아. 모두 함께 모래놀이라도 할래?');
INSERT INTO notif_data VALUES(110301,4,'길드 하우스의 EXP 포션이 가득이야. 이걸 바탕으로 위를 노리자');
INSERT INTO notif_data VALUES(110301,5,'길드 하우스의 마나가 가득 찬 것 같아. 새로운 비즈니스의 자본이 될까?');
INSERT INTO notif_data VALUES(110301,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찬 것 같아. 쌓아두면 나중에 힘들다?');
INSERT INTO notif_data VALUES(110401,1,'어이, 스태미나가 전부 회복됐어. 해변이라도 모험하러 가자. 나도 함께 가줄 테니까!');
INSERT INTO notif_data VALUES(110401,2,'길드 하우스의 스킵 티켓이 가득이야. 전투는 재빨리 끝내고 수영이라도 하러 가자');
INSERT INTO notif_data VALUES(110401,3,'길드 하우스의 스태미나가 가득이군. 좋아, 어디든 따라가 줄게!');
INSERT INTO notif_data VALUES(110401,4,'길드 하우스의 EXP 포션이 가득 찬 것 같아. 강해지는 건 좋은 일이야. 지킬 수 있는 녀석이 늘어나니까!');
INSERT INTO notif_data VALUES(110401,5,'길드 하우스의 마나가 가득 찼다고 해. 뭐에 쓸지 모르지만, 나중에 곤란해지지 않도록 해');
INSERT INTO notif_data VALUES(110401,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼잖아! 어쩔 수 없군, 내가 도와줄 테니까 받으러 가자');
INSERT INTO notif_data VALUES(110501,1,'스태미나가 전부 회복돼서 힘이 넘치고 있어~! 노래하고 춤추며 모험하러 출발하자~!');
INSERT INTO notif_data VALUES(110501,2,'길드 하우스의 스킵 티켓이 가득이야~! 전투를 빨리 끝내고 바다로 뛰어들자~!');
INSERT INTO notif_data VALUES(110501,3,'길드 하우스의 스태미나가 가득이야~! 한참 더 신나게 놀 수 있어~!');
INSERT INTO notif_data VALUES(110501,4,'길드 하우스의 EXP 포션이 가득이야~! 댄스 동작이 좋아질 지도~!');
INSERT INTO notif_data VALUES(110501,5,'길드 하우스의 마나가 가득 찬 것 같은데~? 여름 햇살에 몸을 맡기고 신나게 사용하자~!');
INSERT INTO notif_data VALUES(110501,6,'길드 하우스에서 받을 수 있는 아이템이 전~부 가득 찼어~! 한꺼번에 받고 바다를 만끽하자~!');
INSERT INTO notif_data VALUES(110601,1,'스태미나가 전부 회복했사옵니다. 함께 이상한 나라로 가시지요♪');
INSERT INTO notif_data VALUES(110601,2,'길드 하우스의 스킵 티켓이 가득이옵니다. 서두르는 건 싫지만 왕자님과 함께라면 괜찮사옵니다…♪');
INSERT INTO notif_data VALUES(110601,3,'길드 하우스의 스태미나가 가득이옵니다. 소녀와 함께 바다에서 한껏 놀지 않으시겠어요…?');
INSERT INTO notif_data VALUES(110601,4,'길드 하우스의 EXP 포션이 가득이옵니다. 잔뜩 모아서 단번에 사용하시는 것이옵니까?');
INSERT INTO notif_data VALUES(110601,5,'길드 하우스의 마나가 가득이옵니다. 왕자님은 꾸준하게 모으는 타입이시네요. 근사하옵니다');
INSERT INTO notif_data VALUES(110601,6,'길드 하우스에서 받을 수 있는 아이템이 가득이옵니다! 미라클 마호링… 네? 마법으로 정리하면 아니 되옵니까?');
INSERT INTO notif_data VALUES(107001,1,'스태미나가 전부 회복됐어요. 이걸로 외톨이를 끝낼 수 있을까요…?');
INSERT INTO notif_data VALUES(107001,2,'길드 하우스의 스킵 티켓이 가득이에요…! 친구 사귈 때… 쓸 수 없겠죠. 그렇겠죠…');
INSERT INTO notif_data VALUES(107001,3,'길드 하우스의 스태미나가 가득 차 있었요! 어쩌죠, 자기소개 연습이라도 할까요!?');
INSERT INTO notif_data VALUES(107001,4,'길드 하우스의 EXP 포션이 가득… 이걸 단숨에 마시면 성장해서 친구도…!?');
INSERT INTO notif_data VALUES(107001,5,'길드 하우스의 마나가 가득이에요! 새로운 마이 프렌즈 군을 새로 만들어도 될까요…?');
INSERT INTO notif_data VALUES(107001,6,'길드 하우스에서 받을 수 있는 아이템이 가득이라 주체할 수 없게 된 것 같아요… 마치 다른 사람과 대화하는 때의 저처럼…!');
INSERT INTO notif_data VALUES(110701,1,'스태미나가 전부 회복했습니다. 이걸로 외톨이를 끝낼 수 있을까요…?');
INSERT INTO notif_data VALUES(110701,2,'길드 하우스의 스킵 티켓이 가득이에요…! 친구 사귈 때… 쓸 수 없겠죠. 그렇겠죠…');
INSERT INTO notif_data VALUES(110701,3,'길드 하우스의 스태미나가 가득 차 있었요! 어쩌죠, 자기소개 연습이라도 할까요!?');
INSERT INTO notif_data VALUES(110701,4,'길드 하우스의 EXP 포션이 가득… 이걸 단숨에 마시면 성장해서 친구도…!?');
INSERT INTO notif_data VALUES(110701,5,'길드 하우스의 마나가 가득이에요! 괜찮아 마이 프렌즈 군을 새로 만들어도 될까요…?');
INSERT INTO notif_data VALUES(110701,6,'길드 하우스에서 받을 수 있는 아이템이 가득이라 주체할 수 없게 된 것 같아요… 마치 사람과 대화하는 때의 저처럼…!');
INSERT INTO notif_data VALUES(110801,1,'잠깐, 위험해, 스태미나가 전부 회복됐어. 뭔가 하는 편이 좋지 않을까, 잘 모르겠지만');
INSERT INTO notif_data VALUES(110801,2,'웃긴다. 길드 하우스의 스킵 티켓, 흘러넘칠 것 같은데');
INSERT INTO notif_data VALUES(110801,3,'웃긴다. 길드 하우스의 스태미나, 흘러넘칠 것 같은데');
INSERT INTO notif_data VALUES(110801,4,'웃긴다. 길드 하우스의 EXP 포션, 흘러넘칠 것 같은데');
INSERT INTO notif_data VALUES(110801,5,'웃긴다. 길드 하우스의 마나, 흘러넘칠 것 같은데');
INSERT INTO notif_data VALUES(110801,6,'큰일이야. 길드 하우스에서 받을 수 있는 아이템, 전부 꽉 찼어. 슬슬 받으러 와줄래');
INSERT INTO notif_data VALUES(111101,1,'스태미나가 전부 회복됐어요. 함께 할로윈 파티, 가실래요? 어쩔 수 없으니 따라가 줄게요');
INSERT INTO notif_data VALUES(111101,2,'길드 하우스의 스킵 티켓이 가득 찼잖아요. 서두르다 넘어지면 안 돼요?');
INSERT INTO notif_data VALUES(111101,3,'길드 하우스의 스태미나가 가득 찼는데요? 당신도 분장하고 과자 받으러 갈래요?');
INSERT INTO notif_data VALUES(111101,4,'길드 하우스의 EXP 포션이 가득이에요. 성장하면 과자를 받을 수 없게 될까요…?');
INSERT INTO notif_data VALUES(111101,5,'길드 하우스의 마나가 가득이니, 과자 만들지 않을래요? 아이들에게 나눠줄 거요. 물론 당신에게도 드릴 거예요.');
INSERT INTO notif_data VALUES(111101,6,'길드 하우스에서 받을 수 있는 아이템이 가득 찼잖아요! 빨리 받고 할로윈을 즐겨요!');
INSERT INTO notif_data VALUES(111201,1,'오빠, 스태미나가 전부 회복됐어! 할로윈 파티하자!');
INSERT INTO notif_data VALUES(111201,2,'길드 하우스의 스킵 티켓이 가득 찼대! 트릭 오어 티켓~!');
INSERT INTO notif_data VALUES(111201,3,'길드 하우스의 스태미나가 가득 찼어! 과자 남았으면 미소기한테 줘!');
INSERT INTO notif_data VALUES(111201,4,'길드 하우스의 EXP 포션이 가득이야! 이걸로 엄청난 장난을 칠 수 있을지도!');
INSERT INTO notif_data VALUES(111201,5,'길드 하우스의 마나가 가득 찼어! 이걸로 미소기한테 과자 사 줄래~?');
INSERT INTO notif_data VALUES(111201,6,'길드 하우스의 아이템이 가득 찼어! 아무런 장치도 안 했으니까 받으러 와! 이히히♪');
INSERT INTO notif_data VALUES(111301,1,'스태미나가 전부 회복됐대, 오빠! 미미랑 할로윈 퍼레이드 하자~♪');
INSERT INTO notif_data VALUES(111301,2,'에헤헤, 트릭 오어 트릿~♪ 길드 하우스의 스킵 티켓이 가득 찼어, 오빠!');
INSERT INTO notif_data VALUES(111301,3,'오빠, 길드 하우스의 스태미나가 가득이야! 할로윈 의상 입고 외출하자~♪');
INSERT INTO notif_data VALUES(111301,4,'오빠! 길드 하우스의 EXP 포션이 가득이니까 잔뜩 써서 즐겁게 할로윈을 보내자~♪');
INSERT INTO notif_data VALUES(111301,5,'길드 하우스의 마나가 가득 찼대! 오빠, 미미 과자도 사주려나…');
INSERT INTO notif_data VALUES(111301,6,'오빠! 길드 하우스의 아이템이 전부 가득 찬 것 같아! 에헤헤, 해피 할로윈~♪');
COMMIT;
